name: 'Deploy site to production'
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.15.x
          cache: npm

      - name: Install dependencies and build
        run: npm run ci

      - name: Install server dependencies
        uses: "php-actions/composer@v6"
        env:
          COMPOSER: "composer.json"
        with:
          php_version: "7.4.33"
          working_dir: "server"

      - name: Create server env file
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_ENVIRONMENT: PRODUCTION
          envkey_SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          directory: dist/api
          file_name: .env
          fail_on_empty: false
          sort_keys: false

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ vars.FTP_HOSTNAME }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./build/
          server-dir: ./public_html/
          dangerous-clean-slate: true
